version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - next-cache:/app/.next/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=development
volumes:
  next-cache:
    driver: local
